version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
      - '*'
  reviewers:
  - jasmeralia
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  groups:
    npm-tools:
      patterns:
      - '*'
  reviewers:
  - jasmeralia
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
